### ISSUE TITLE
404 error if username/password or tokens are used

### ISSUE THREAD

**Issue by goegol** [Chouffy/home_assistant_tgtg#11] opened 2021-11-18 13:17 UTC
Hi, 

When i use the python code i got an 404

`tgtg.exceptions.TgtgLoginError: (404, b'')
`

**Comment by Chouffy** [comment] 2021-11-19 08:09
Hi @goegol,
Could you please elaborate? which python code are you referring to?

**Comment by TanguyOrtegat** [comment] 2021-11-19 08:49
yes error 404, now when you want to login to tgtg, you enter email in the app, then tgtg sends you and email that you need to accept and then you are automaticly logged in to the app. no password needed anymore

**Comment by Chouffy** [comment] 2021-11-19 09:13
Did you check the top of the script, with a suggested way to reset your password? https://github.com/Chouffy/home_assistant_tgtg/blob/main/tgtg_get_tokens.py#L7

**Comment by TanguyOrtegat** [comment] 2021-11-19 09:23
> id you check the top of the script, with a suggested way

I have a password normally, tgtg changed way of working

**Comment by goegol** [comment] 2021-11-19 09:30
@Chouffy i use you're example python script.
The reset password is not working for me (create also seperate, new, account on gmail address). I didn't receive any password reset mail.

When i run the script i got a 404 (404 page / api not found, i expect other http code if password is wrong / not usable)

`Traceback (most recent call last):
  File "/home/goegol/tgto.py", line 17, in <module>
    client.get_items()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 147, in get_items
    self.login()
  File "/root/.local/share/virtualenvs/goegol-54Koo1qd/lib/python3.9/site-packages/tgtg/__init__.py", line 126, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (404, b'')`

**Comment by Chouffy** [comment] 2021-11-19 10:10
Indeed you're right, I can reproduce that on my PC:
* If you have username/password combo, you get this 404 error ... this is since few days then.
* If you have the 3 token, it still works fine

Unfortunately I cannot do anything on my side as I just use the `tgtg-python` module - so it's good that you already [create an issue](https://github.com/ahivert/tgtg-python/issues/121)
Let's see if we can find a way to retrieve those tokens ...

**Comment by lampje25** [comment] 2021-11-19 20:14
same problems here.
this morning it still worked.
Not anymore unfortunately.

**Comment by groenmarsmannetje** [comment] 2021-11-24 10:00
Since yesterday I also get 404 errors, but I was already using the tokens.

**Comment by Chouffy** [comment] 2021-11-24 14:15
@groenmarsmannetje  Indeed, I can also reproduce this issue ... Another issue has been registered on the upstream module here: https://github.com/ahivert/tgtg-python/issues/124
Hopefully we'll be able to find a way to log in 🤞

**Comment by wieluk** [comment] 2021-11-25 17:17
upstream got fixed with version 0.8 it works like this for me: 
```
client = TgtgClient(email="you@mail.com")
tgtg_id = client.get_credentials()
client = TgtgClient(access_token=tgtg_id['access_token'], refresh_token=tgtg_id['refresh_token'], user_id=tgtg_id['user_id'])
client.login() 
```
unfortunately you get a email every time. So we have to try to use tokens as long as they work and then retry with email.

**Comment by wieluk** [comment] 2021-12-02 13:09
It works now with version 0.10.0

**Comment by groenmarsmannetje** [comment] 2021-12-02 14:16
Yes I got it also working again after I updated the version number in manifest file.

**Comment by Chouffy** [comment] 2021-12-02 15:42
Awesome! I'll work on it later today and push an update

**Comment by Chouffy** [comment] 2021-12-03 04:47
Hi all, the new release should fix the login issue: now it's with token only. Check out the Readme for more info!

**Closed by Chouffy** 2021-12-03 04:47 UTC
Labels: bug, upstream module

**Comment by nepozs** [comment] 2021-12-07 01:57
It does not help - email is redirecting to link looking like:

`https://space.toogoodtogo.com/login/accept/12345687/1cbc122b-b112-191c-860d-f1e2b70b2f67`
but script ends like this:
```
Type your email linked to your TGTG account: my_email@here
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Check your mailbox on PC to continue... (Mailbox on mobile won't work, if you have installed tgtg app.)
Traceback (most recent call last):
  File "c:/ha/tgtg_tokens.py", line 11, in <module>
    tgtgClient.get_credentials()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\tgtg\__init__.py", line 67, in get_credentials
    self.login()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\tgtg\__init__.py", line 139, in login
    self.start_polling(first_login_response["polling_id"])
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\tgtg\__init__.py", line 182, in start_polling
    raise TgtgPollingError(
tgtg.exceptions.TgtgPollingError: Max retries (120 seconds) reached. Try again.
```
