### ISSUE TITLE
error after restarting HA

### ISSUE THREAD

**Issue by lampje25** [Chouffy/home_assistant_tgtg#49] opened 2023-01-21 09:30 UTC
Logger: homeassistant.components.sensor
Source: custom_components/tgtg/sensor.py:186
Integration: Sensor (documentation, issues)
First occurred: 10:18:56 (1 occurrences)
Last logged: 10:18:56

Error while setting up tgtg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tgtg/sensor.py", line 73, in setup_platform
    add_entities([TGTGSensor(each_item_id)])
  File "/config/custom_components/tgtg/sensor.py", line 93, in __init__
    self.update()
  File "/config/custom_components/tgtg/sensor.py", line 186, in update
    self.tgtg_answer = tgtg_client.get_item(item_id=self.item_id)
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 262, in get_item
    self.login()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 139, in login
    self._refresh_token()
  File "/usr/local/lib/python3.10/site-packages/tgtg/__init__.py", line 129, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'rt\':\'c\',\'cid\':\'AHrlqAAAAAMAO6flr6g6whAA9rTuBw==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35558,\'e\':\'bf9fe76e3a1cf80d26a431ff0ff9f1c744ae00fd1d9fe2db0516c82ca0f7e91f\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')

**Comment by JustAnyGitHubUser** [comment] 2023-01-21 13:22
Good news is, that you are not the only one with this issues :)
It seems to be related to this issue [https://github.com/ahivert/tgtg-python/issues/205](url)

**Comment by Chouffy** [comment] 2023-01-22 09:24
Duplicate of #37  that I've just reopened :)

**Closed by Chouffy** 2023-01-22 09:24 UTC
